import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const products = [
  { id: 0,  name: "The Equalizer",      price: 5.99, category: "Action",           stock: 5,  year: 2014, rating: "7.2", director: "Antoine Fuqua",      cast: "Denzel Washington, Marton Csokas, Chloë Grace Moretz", image: "https://upload.wikimedia.org/wikipedia/en/8/85/The_Equalizer_%282021_TV_series%29_Title_Card.png",       description: "A man believes he has put his mysterious past behind him and settled into a quiet life. But when he meets a young girl under the control of ultra-violent Russian gangsters, he can't walk away." },
  { id: 1,  name: "Inception",          price: 3.99, category: "Sci-Fi",           stock: 10, year: 2010, rating: "8.8", director: "Christopher Nolan",   cast: "Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page", image: "https://wallpapers.com/images/hd/inception-movie-title-graphic-37pec2s1d1hrg3ih.jpg",                       description: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O." },
  { id: 2,  name: "The Dark Knight",    price: 4.50, category: "Action",           stock: 0,  year: 2008, rating: "9.0", director: "Christopher Nolan",   cast: "Christian Bale, Heath Ledger, Aaron Eckhart",          image: "https://batman-on-film.com/wp-content/uploads/2018/07/TDK-logo.jpg",                                            description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological tests of his ability to fight injustice." },
  { id: 3,  name: "Interstellar",       price: 5.50, category: "Sci-Fi",           stock: 3,  year: 2014, rating: "8.6", director: "Christopher Nolan",   cast: "Matthew McConaughey, Anne Hathaway, Jessica Chastain", image: "https://q30tv.com/wp-content/uploads/2014/11/interstellar-poster-1024x576.jpg",                                 description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival as Earth faces an environmental collapse." },
  { id: 4,  name: "The Matrix",         price: 2.99, category: "Classics",         stock: 8,  year: 1999, rating: "8.7", director: "The Wachowskis",      cast: "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss",   image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRpYyualeC5paFx3kEoCr2i97qP0HydnT2Jtw&s",               description: "When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth: the life he knows is the elaborate deception of an evil cyber-intelligence." },
  { id: 5,  name: "Gladiator",          price: 3.50, category: "Action",           stock: 4,  year: 2000, rating: "8.5", director: "Ridley Scott",        cast: "Russell Crowe, Joaquin Phoenix, Connie Nielsen",       image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRKJ7pLuN2V-1mY_0T8OiyLx5LyJWf_wuAog&s",               description: "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery." },
  { id: 6,  name: "Jurassic Park",      price: 2.50, category: "Family & Kids",    stock: 12, year: 1993, rating: "8.1", director: "Steven Spielberg",    cast: "Sam Neill, Laura Dern, Jeff Goldblum",                 image: "https://grapheine.com/wp-content/uploads/2019/11/jp-cover.webp",                                                description: "A pragmatic paleontologist visits a theme park populated with dinosaurs created from prehistoric DNA. Things quickly unravel when the dinosaurs break free." },
  { id: 7,  name: "Dune: Part Two",     price: 9.99, category: "New Releases",     stock: 15, year: 2024, rating: "8.5", director: "Denis Villeneuve",    cast: "Timothée Chalamet, Zendaya, Rebecca Ferguson",         image: "https://i.pinimg.com/736x/67/35/8b/67358b3a179a8d7483db0a83d6b934f2.jpg",                                     description: "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family. Facing a choice between love and destiny." },
  { id: 8,  name: "Oppenheimer",        price: 6.50, category: "Highest Rated",    stock: 7,  year: 2023, rating: "8.9", director: "Christopher Nolan",   cast: "Cillian Murphy, Emily Blunt, Matt Damon",              image: "https://m.media-amazon.com/images/S/aplus-media-library-service-media/fb00d909-d7b2-458b-8fa7-3ab8a843fec9.__CR0,0,970,300_PT0_SX970_V1___.jpg", description: "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II." },
  { id: 9,  name: "Pulp Fiction",       price: 3.00, category: "Classics",         stock: 0,  year: 1994, rating: "8.9", director: "Quentin Tarantino",   cast: "John Travolta, Uma Thurman, Samuel L. Jackson",        image: "https://alexsheremet.com/wp-content/uploads/2016/02/Pulp-Fiction-Logo-Tarantino.jpg",                           description: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption." },
  { id: 10, name: "The Godfather",      price: 7.99, category: "Classics",         stock: 2,  year: 1972, rating: "9.2", director: "Francis Ford Coppola", cast: "Marlon Brando, Al Pacino, James Caan",                 image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/The_Godfather_Logo.webp/400px-The_Godfather_Logo.webp.png", description: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son." },
  { id: 11, name: "Avatar",             price: 4.99, category: "Sci-Fi",           stock: 9,  year: 2009, rating: "7.9", director: "James Cameron",       cast: "Sam Worthington, Zoe Saldana, Sigourney Weaver",       image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Avatar-Logo-avatar.svg/1280px-Avatar-Logo-avatar.svg.png", description: "A paraplegic marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting the alien civilization he is sent to invade." },
  { id: 12, name: "The Avengers",       price: 4.50, category: "Action",           stock: 6,  year: 2012, rating: "8.0", director: "Joss Whedon",         cast: "Robert Downey Jr., Chris Evans, Scarlett Johansson",   image: "https://i.pinimg.com/736x/19/10/68/19106875a6603576111ba924bb15c12a.jpg",                                     description: "Earth's mightiest heroes must come together and learn to fight as a team if they are going to stop the mischievous Loki and his alien army from enslaving humanity." },
  { id: 13, name: "John Wick",          price: 5.50, category: "Action",           stock: 1,  year: 2014, rating: "7.4", director: "Chad Stahelski",      cast: "Keanu Reeves, Michael Nyqvist, Alfie Allen",           image: "https://straightfromamovie.com/wp-content/uploads/2015/02/john-wick.jpg",                                       description: "An ex-hitman comes out of retirement to track down the gangsters who killed his beloved dog and took everything from him." },
  { id: 14, name: "The Batman",         price: 7.99, category: "Mystery & Thriller", stock: 4, year: 2022, rating: "7.8", director: "Matt Reeves",        cast: "Robert Pattinson, Zoë Kravitz, Paul Dano",             image: "https://deadline.com/wp-content/uploads/2020/08/batman-e1597940464165.jpg",                                     description: "When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city's hidden corruption." },
  { id: 15, name: "Top Gun: Maverick",  price: 6.99, category: "Highest Rated",    stock: 11, year: 2022, rating: "8.3", director: "Joseph Kosinski",     cast: "Tom Cruise, Miles Teller, Jennifer Connelly",          image: "https://thumbnails.cbsig.net/_x/w1200/CBS_Production_Entertainment_VMS/2022/10/26/2091444291941/TGMAV_SAlone_16_9_1920x1080_1781067_1920x1080.jpg", description: "After more than thirty years of service as a top naval aviator, Pete Mitchell is back, pushing the envelope as a courageous test pilot and dodging the advancement in rank." },
  { id: 16, name: "Spider-Man",         price: 4.50, category: "Family & Kids",    stock: 5,  year: 2002, rating: "7.4", director: "Sam Raimi",           cast: "Tobey Maguire, Kirsten Dunst, Willem Dafoe",           image: "https://www.meewella.com/critic/images/film/spidermanp.jpg",                                                    description: "When bitten by a genetically modified spider, a nerdy, shy, and awkward high school student gains spider-like abilities that he eventually must use to fight evil as a superhero." },
  { id: 17, name: "No Time To Die",     price: 5.50, category: "Action",           stock: 0,  year: 2021, rating: "7.3", director: "Cary Joji Fukunaga",  cast: "Daniel Craig, Rami Malek, Léa Seydoux",               image: "https://ntvb.tmsimg.com/assets/p15454352_v_h10_ak.jpg?w=1280&h=720",                                            description: "James Bond has left active service. His peace is short-lived when Felix Leiter, an old friend from the CIA, turns up asking for help, leading Bond onto the trail of a mysterious villain." },
  { id: 18, name: "Columbo: Mystery Movie Collection (1989 -1990)", price: 7.99, category: "Mystery & Thriller", stock: 4,  year: 1971, rating: "8.3", director: "Various", cast: "Peter Falk", image: "https://m.media-amazon.com/images/S/pv-target-images/6435c28aa73adbe325dac934ab97402422ab72236e9f26d867f556ac3102ec4a.jpg", description: "A collection of feature-length television mysteries following Lieutenant Columbo as he solves seemingly perfect crimes using his unassuming demeanor and sharp intellect." },
  { id: 19, name: "The Naked Gun: From the Files of Police Squad!",           price: 4.99, category: "Comedy",             stock: 2,  year: 1988, rating: "7.6", director: "David Zucker",      cast: "Leslie Nielsen, Priscilla Presley, O.J. Simpson",   image: "https://miro.medium.com/v2/resize:fit:1400/0*daePliker6zatyd2.jpg", description: "Incompetent police lieutenant Frank Drebin must foil an attempt to assassinate Queen Elizabeth II." },
  { id: 20, name: "Star Wars: Episode IV",   price: 4.50, category: "Sci-Fi",             stock: 10, year: 1977, rating: "8.6", director: "George Lucas",      cast: "Mark Hamill, Harrison Ford, Carrie Fisher",         image: "https://api.triviacreator.com/v1/imgs/quiz/3adcbdf3-3490-4ba3-8acd-52ec32ed9221-5a94a911-9742-4f01-82a2-ee4e58332b62.png", description: "Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, and two droids to save the galaxy from the Empire's world-destroying battle station." },
  { id: 21, name: "Knives Out",              price: 5.50, category: "Mystery & Thriller", stock: 3,  year: 2019, rating: "7.9", director: "Rian Johnson",       cast: "Daniel Craig, Chris Evans, Ana de Armas",           image: "https://davidkummer.com/wp-content/uploads/2023/07/knives-out.jpg", description: "A detective investigates the death of a patriarch of an eccentric, combative family." },
  { id: 22, name: "Predator: Badlands", price: 7.99, category: "New Releases", stock: 0, year: 2025, rating: "TBD", director: "Dan Trachtenberg", cast: "Elle Fanning", image: "https://thecosmiccircus.com/wp-content/uploads/2025/11/predator-badlands-review-1.jpg", description: "A standalone installment in the Predator franchise set in a remote wasteland, where humanity once again encounters the deadly alien hunter in a brutal fight for survival." },
  { id: 23, name: "The Shining",             price: 9.99, category: "Highest Rated",     stock: 5,  year: 1980, rating: "8.4", director: "Stanley Kubrick",    cast: "Jack Nicholson, Shelley Duvall",                    image: "https://i0.wp.com/bluraydownlow.wordpress.com/wp-content/uploads/2019/10/the-shining-facebook-cover.jpg?fit=1200%2C675&ssl=1&w=640", description: "A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence." },
  { id: 24, name: "The Super Mario Bros. Movie", price: 4.50, category: "Family & Kids", stock: 8, year: 2023, rating: "7.0", director: "Aaron Horvath", cast: "Chris Pratt, Anya Taylor-Joy, Jack Black", image: "https://www.peacocktv.com/dam/growth/assets/Campaign/P1/SuperMarioBros/mario-social.jpg", description: "Brooklyn plumbers Mario and Luigi are transported to a magical world, where Mario teams up with Princess Peach and others to stop Bowser from conquering the Mushroom Kingdom." },
  { id: 25, name: "Spirited Away",           price: 7.99, category: "Classics",           stock: 6,  year: 2001, rating: "8.6", director: "Hayao Miyazaki",     cast: "Rumi Hiiragi, Miyu Irino",                          image: "https://i2.wp.com/attackongeek.com/wp-content/uploads/2018/03/Spirited_Away_Wallpaper_by_behruz-e1414155694995-2.jpg?fit=768%2C377&ssl=1", description: "During her family's move to the suburbs, a 10-year-old girl wanders into a world ruled by gods, witches, and spirits." },
  { id: 26, name: "Game of Thrones: The Complete Series", price: 19.99, category: "New Releases", stock: 4, year: 2011, rating: "9.2", director: "Various", cast: "Emilia Clarke, Peter Dinklage, Kit Harington", image: "https://savethecat.com/wp-content/uploads/2016/06/Game-of-Thrones-Season-1.jpg", description: "Noble families vie for control of the Iron Throne in the land of Westeros, while an ancient supernatural threat rises beyond the Wall." },
  { id: 27, name: "Madea Goes to Jail",      price: 4.50, category: "Comedy",             stock: 9,  year: 2009, rating: "4.5", director: "Tyler Perry",       cast: "Tyler Perry, Blair Underwood",                      image: "https://ntvb.tmsimg.com/assets/p186862_v_h10_ab.jpg?w=1280&h=720",        description: "After a high-speed freeway chase, Madea is sent to jail, where she meets a variety of characters and offers her unique brand of advice." },
  { id: 28, name: "Scream VI",               price: 5.50, category: "Mystery & Thriller", stock: 2,  year: 2023, rating: "6.5", director: "Matt Bettinelli",     cast: "Melissa Barrera, Jenna Ortega",                     image: "https://www.paramountmovies.com/uploads/movies/scream-vi/screamvi-pm-share-1200x630.png", description: "The survivors of the Ghostface killings leave Woodsboro behind and start a fresh chapter in New York City." },
  { id: 29, name: "The Wizard of Oz",        price: 7.99, category: "Classics",           stock: 0,  year: 1939, rating: "8.1", director: "Victor Fleming",     cast: "Judy Garland, Frank Morgan",                        image: "https://beam-images.warnermediacdn.com/BEAM_LWM_DELIVERABLES/18a7f5a2-3f3a-4a62-a257-29136ac68dff/6aa2a3a6-e201-4aba-8eaa-04c1f31a7823?host=wbd-images.prod-vod.h264.io&partner=beamcom", description: "Dorothy Gale is swept away from a farm in Kansas to a magical land of Oz and embarks on a quest with her new friends." },
  { id: 30, name: "Alien: 6-Film Collection", price: 19.99, category: "Sci-Fi", stock: 3, year: 2017, rating: "8.5", director: "Various", cast: "Sigourney Weaver", image: "https://pbs.twimg.com/media/GJS60AOW4AAJtPQ.jpg", description: "A sci-fi horror saga following humanity’s terrifying encounters with the deadly Xenomorph species, spanning from the Nostromo to deep-space colonization missions." },
  { id: 31, name: "Static Shock: The Complete First Season",  price: 4.50, category: "Family & Kids",      stock: 15, year: 2000, rating: "7.3", director: "Various",           cast: "Phil LaMarr, Jason Marsden",                        image: "https://m.media-amazon.com/images/S/pv-target-images/51298a97b0e91c7fca3a193a1f0947ff9797b71372a8e1709e1f1ca2ece9b764.jpg",        description: "After being exposed to a strange gas, Virgil Hawkins gains the power to control electromagnetism and becomes a superhero." },
  { id: 32, name: "Brooklyn Nine-Nine: Season 3",  price: 5.50, category: "Comedy",             stock: 7,  year: 2015, rating: "8.4", director: "Various",           cast: "Andy Samberg, Stephanie Beatriz, Terry Crews",      image: "https://m.media-amazon.com/images/S/pv-target-images/52371036368023ea0560a34366bd4669914e282c55166c1952e9393acf5b22cd.jpg", description: "Jake Peralta and his lovable colleagues at the NYPD's 99th Precinct continue their hilarious crime-fighting antics." },
  { id: 33, name: "Sonic the Hedgehog 3", price: 8.99, category: "Action", stock: 5, year: 2024, rating: "7.2", director: "Jeff Fowler", cast: "Ben Schwartz, Keanu Reeves, Jim Carrey", image: "https://thecollision.org/wp-content/uploads/2024/12/sonic3.png", description: "Sonic, Tails, and Knuckles face their most formidable foe yet when the mysterious and powerful Shadow emerges, threatening the safety of Earth." },
  { id: 34, name: "Liar Liar",               price: 3.50, category: "Comedy",             stock: 4,  year: 1997, rating: "6.9", director: "Tom Shadyac",       cast: "Jim Carrey, Maura Tierney",                         image: "https://www.acmodasi.in/amdb/images/movie/x/1/liar-liar-1997-75452.jpg",        description: "A fast-talking lawyer's life turns upside down when his son's birthday wish forces him to tell the truth for 24 hours." },
  { id: 35, name: "How to Train Your Dragon", price: 2.50, category: "Family & Kids",     stock: 0,  year: 2010, rating: "8.1", director: "Dean DeBlois",      cast: "Jay Baruchel, Gerard Butler",                       image: "https://images.squarespace-cdn.com/content/v1/54400c3de4b06a018e97259e/df065393-55e9-4145-b07a-3c93ab9b81ea/AAAABYuoBJ8JQWVPnv7rmbLLfRZoIigxFxqz2JlHIpQkdU_tN31tzZ3cYu8uYkwOk5_6Bjklz2HkvGx_PqOPQTc7LJqkyhSb.jpg",        description: "A hapless young Viking who aspires to hunt dragons becomes the unlikely friend of a young dragon himself." },
  { id: 36, name: "Five Nights at Freddy's 2", price: 12.99, category: "Mystery & Thriller", stock: 6, year: 2025, rating: "TBD", director: "Emma Tammi", cast: "Josh Hutcherson, Matthew Lillard", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZFXcdkVOq3x53OQyx0Obf6m4YawNeD2BH2w&s", description: "The nightmare continues as new animatronic horrors and deeper secrets surrounding Freddy Fazbear’s Pizza terrorize those who dare to return." },
  { id: 37, name: "Michael Jackson: This Is It", price: 6.50, category: "Highest Rated",  stock: 10, year: 2009, rating: "7.2", director: "Kenny Ortega",      cast: "Michael Jackson",                                   image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpK9f3g_3BH5sXDN734S7NfVbdQbSE2uosew&s", description: "A compilation of interviews, rehearsals, and backstage footage of Michael Jackson as he prepared for his sold-out shows." },
  { id: 38, name: "Space Jam",               price: 3.00, category: "Classics",           stock: 12, year: 1996, rating: "6.5", director: "Joe Pytka",         cast: "Michael Jordan, Wayne Knight, Danny DeVito",        image: "https://m.media-amazon.com/images/S/pv-target-images/97626a18861e3a416cd25d6ae969eb29aba09f3b8eb9e9c05d75ddeedd73d96c.jpg", description: "In a desperate attempt to win a basketball match, the Looney Tunes seek the aid of retired champion Michael Jordan." },
  { id: 39, name: "Mortal Kombat (2021)",    price: 7.99, category: "Action",             stock: 8,  year: 2021, rating: "6.0", director: "Simon McQuoid",     cast: "Lewis Tan, Jessica McNamee",                        image: "https://m.media-amazon.com/images/S/pv-target-images/a2ee8d8fa44f1b09b5ddbb8cb723bf12f8f0de25c79b0527867c9966d39de8b1.jpg", description: "MMA fighter Cole Young seeks out Earth's greatest champions in order to stand against the enemies of Outworld." },
  { id: 40, name: "Fallout: Season One", price: 13.99, category: "New Releases", stock: 2, year: 2024, rating: "8.4", director: "Jonathan Nolan", cast: "Ella Purnell, Aaron Moten, Walton Goggins", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbrDxUJUSAGsoPbqrsjXKQKuwaIL35mRX3xA&s", description: "In a retro-futuristic post-apocalyptic world, survivors emerge from underground vaults and navigate a brutal wasteland filled with factions, mutants, and dark secrets." },
  { id: 41, name: "Batman: Brave & the Bold: Season 2", price: 4.50, category: "Family & Kids", stock: 5, year: 2008, rating: "7.3", director: "Various", cast: "Diedrich Bader", image: "https://m.media-amazon.com/images/S/pv-target-images/ca7c58d72ba6daa3785d2344dbe57e5a5edfdac7058c0763f090495e82592623.jpg", description: "Batman joins forces with heroes from across the DC Universe in bold, action-packed adventures to stop colorful villains and protect the world." },
  { id: 42, name: "Five Nights at Freddy's", price: 5.50, category: "Mystery & Thriller", stock: 0,  year: 2023, rating: "5.4", director: "Emma Tammi",        cast: "Josh Hutcherson, Mary Stuart Masterson",            image: "https://m.media-amazon.com/images/S/pv-target-images/86a7f288af275fda17ca47c8e832b0eb7058c1316ef192628d04d453b706c0c5._UR1920,1080_.jpg", description: "A troubled security guard begins working at Freddy Fazbear's Pizzeria and realizes the night shift won't be easy." },
  { id: 43, name: "Toy Story 3",             price: 7.99, category: "Classics",           stock: 3,  year: 2010, rating: "8.3", director: "Lee Unkrich",       cast: "Tom Hanks, Tim Allen",                              image: "https://disney.images.edge.bamgrid.com/ripcut-delivery/v2/variant/disney/ba9289c1-87ce-4e88-86a7-b5c937ae3af2/compose?aspectRatio=1.78&format=webp&width=1200", description: "The toys are mistakenly delivered to a day-care center right before Andy leaves for college." },
  { id: 44, name: "Blade Runner 2049",       price: 9.99, category: "Highest Rated",     stock: 7,  year: 2017, rating: "8.0", director: "Denis Villeneuve",   cast: "Ryan Gosling, Harrison Ford",                       image: "https://m.media-amazon.com/images/S/pv-target-images/9b72c225199a14df69571c38f27d08bd91725d76f9c7b23c711f083b5bce31f9.jpg", description: "Young Blade Runner K's discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard." },
  { id: 45, name: "Scooby-Doo on Zombie Island", price: 4.50, category: "Family & Kids",    stock: 20, year: 1998, rating: "7.7", director: "Jim Stenstrum",     cast: "Scott Innes, Billy West",                           image: "https://m.media-amazon.com/images/S/pv-target-images/8053099106c2f85b38b21b20b11d90008b9f822006d1d0878d40ab78d161d58e.jpg",        description: "The Mystery Gang reunites to visit a haunted island, only to find themselves facing real ghosts and zombies." },
  { id: 46, name: "Uncharted",               price: 5.50, category: "Mystery & Thriller", stock: 1,  year: 2022, rating: "6.3", director: "Ruben Fleischer",    cast: "Tom Holland, Mark Wahlberg",                        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIXm-KOur7V5-LP7ydMTApgH46WkZPxqudcQ&s", description: "Street-smart Nathan Drake is recruited by seasoned treasure hunter Sully to recover a fortune lost 500 years ago." },
  { id: 47, name: "GoldenEye", price: 7.99, category: "Classics", stock: 5, year: 1995, rating: "7.2", director: "Martin Campbell", cast: "Pierce Brosnan, Sean Bean", image: "https://ntvb.tmsimg.com/assets/p17416_v_h10_az.jpg?w=1280&h=720", description: "James Bond faces a rogue former agent who plans to use a powerful satellite weapon known as GoldenEye to devastate London." },
  { id: 48, name: "Superman (2025)", price: 9.99, category: "New Releases", stock: 0, year: 2025, rating: "TBD", director: "James Gunn", cast: "David Corenswet, Rachel Brosnahan", image: "https://m.media-amazon.com/images/S/pv-target-images/f88dcfc4e91ee92c30207ff65378038aa7a91a6f550402d55954412e882b6b10.jpg", description: "A reimagining of the Man of Steel’s story, exploring Clark Kent’s struggle to balance his Kryptonian heritage with his life as a human reporter in Metropolis." },
  { id: 49, name: "Captain Underpants: The First Epic Movie",      price: 4.50, category: "Family & Kids",      stock: 6,  year: 2017, rating: "6.2", director: "David Soren",       cast: "Kevin Hart, Ed Helms",                              image: "https://m.media-amazon.com/images/S/pv-target-images/24c8b4b9b35957f97ab135bb707a4cf753d8a423ba9f8c4bd07075200af8a9ab.jpg", description: "Two imaginative pranksters hypnotize their principal into thinking he's a superhero named Captain Underpants." },
  { id: 50, name: "Star Trek: First Contact", price: 5.50, category: "Sci-Fi",            stock: 4,  year: 1996, rating: "7.6", director: "Jonathan Frakes",   cast: "Patrick Stewart, Jonathan Frakes",                  image: "https://m.media-amazon.com/images/S/pv-target-images/d1c83cb2f8769de5dfb460ba91400add2a9085e0721b31ecda6f48e4363c1616.jpg", description: "The Borg travel back in time to prevent Earth's first contact. Picard and his crew must follow them." },
  { id: 51, name: "Spider-Man: Into the Spider-Verse",   price: 7.99, category: "Highest Rated",      stock: 3,  year: 2018, rating: "8.4", director: "Peter Ramsey",      cast: "Shameik Moore, Jake Johnson",                       image: "https://m.media-amazon.com/images/S/pv-target-images/6d7e5bcdbf18511aa8931caea5215bb9a5a73cc13fb4b5c45494c0d1828f0699.jpg", description: "Teen Miles Morales joins with spider-powered individuals from other dimensions to stop a threat for all realities." },
  { id: 52, name: "Fast & Furious 8", price: 9.99, category: "Action", stock: 9, year: 2017, rating: "7.5", director: "F. Gary Gray", cast: "Vin Diesel, Dwayne Johnson, Jason Statham", image: "https://m.media-amazon.com/images/S/pv-target-images/fa4b2d240ffdbd7a483f0e702782c480e0490614086fc1c561d3c416232428a6.jpg", description: "Dom Toretto is coerced into betraying his team, forcing the crew to unite against a cyberterrorist who threatens global chaos." },
  { id: 53, name: "The LEGO Ninjago Movie",  price: 4.50, category: "Family & Kids",      stock: 5,  year: 2017, rating: "6.0", director: "Charlie Bean",      cast: "Jackie Chan, Dave Franco",                          image: "https://static3.go3.tv/scale/go3/images-milano/62858cc731587cae7cf76ed5a0898934_WBD_172091_000_BAL_horizontal-title-logo_en-US.jpg?dsth=1080&dstw=1920&srcmode=0&srcx=0&srcy=0&quality=100&type=2&srch=2160&srcw=3840", description: "Six young ninjas are tasked with defending their island home, Ninjago, under the guidance of Master Wu." },
  { id: 54, name: "Scary Movie", price: 5.99, category: "Comedy", stock: 4, year: 2000, rating: "6.3", director: "Keenen I. Wayans", cast: "Anna Faris, Jon Abrahams", image: "https://i.ytimg.com/vi/HTLPULt0eJ4/maxresdefault.jpg", description: "A group of teenagers is targeted by a masked killer in this outrageous parody of popular horror films like Scream and I Know What You Did Last Summer." },
  { id: 55, name: "Pokémon: The First Movie", price: 4.50, category: "Family & Kids",     stock: 0,  year: 1998, rating: "6.3", director: "Kunihiko Yuyama",   cast: "Veronica Taylor, Philip Bartlett",                  image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGbsMEafaYF2hPgf8uoMDn71NlaJNAqK855g&s", description: "Scientists create a genetically enhanced Pokémon named Mewtwo, who decides to challenge the world's greatest trainers." },
  { id: 56, name: "The House with a Clock in its Walls",  price: 5.50, category: "Mystery & Thriller", stock: 2,  year: 2018, rating: "6.1", director: "Eli Roth",          cast: "Jack Black, Cate Blanchett",                        image: "https://m.media-amazon.com/images/S/pv-target-images/2b76b3b47aa0b5a4cc4e7bb38bd0f148f9e7b54e645bcc136fc9b3d9d0947d23.jpg", description: "A young orphan helps his magical uncle locate a clock with the power to bring about the end of the world." },
  { id: 57, name: "Titanic",                 price: 7.99, category: "Classics",           stock: 5,  year: 1997, rating: "7.9", director: "James Cameron",     cast: "Leonardo DiCaprio, Kate Winslet",                   image: "https://m.media-amazon.com/images/S/pv-target-images/4c3f3a742490480050eacfdaec96e6aa7cab88dac5d8a01c29fe36db45f9933a.jpg", description: "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the ill-fated R.M.S. Titanic." },
  { id: 58, name: "A Minecraft Movie", price: 9.99, category: "New Releases", stock: 4, year: 2025, rating: "TBD", director: "Jared Hess", cast: "Jason Momoa, Jack Black", image: "https://beam-images.warnermediacdn.com/BEAM_LWM_DELIVERABLES/05eee581-3112-4515-b17f-219ff6265ef8/96557df6-9268-40e6-9817-91dc86d0f3b4?host=wbd-images.prod-vod.h264.io&partner=beamcom", description: "Four misfits are pulled into the blocky Overworld and must master its crafting rules and survive dangerous creatures to find their way home." },
  { id: 59, name: "American Psycho",         price: 4.50, category: "Mystery & Thriller", stock: 8,  year: 2000, rating: "7.6", director: "Mary Harron",       cast: "Christian Bale, Justin Theroux",                    image: "https://m.media-amazon.com/images/S/pv-target-images/0083e2b6fbdc272e546b0e0e7e5388dd132c7104a938fc860cd45c5188164656.jpg", description: "A wealthy New York investment banking executive hides his alternate psychopathic ego from his co-workers and friends." }
];

async function main() {
  console.log('Cleaning database...');
  await prisma.inventory.deleteMany(); 

  console.log('Seeding Inventory...');
  await prisma.inventory.createMany({
    data: products.map((p) => ({
      id: p.id, 
      name: p.name,
      price: parseFloat(p.price),
      category: p.category,
      stock: parseInt(p.stock),
      year: p.year ? parseInt(p.year) : null,
      rating: p.rating ? parseFloat(p.rating) : null,
      director: p.director || null,
      cast: p.cast || null,
      image: p.image,
      description: p.description || null,
    })),
  });

  console.log('Seed successful!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });